### ISSUE TITLE
Homebrew forumula not available?

### ISSUE THREAD

**Issue by masondesu** [docker/dockercloud-cli#2]
Hey there. I just ran `brew update` and `brew install docker-cloud` per the readme, but the formula isn't found.

Any clue when it will be up or what the correct name of the formula is?

Thanks!

**Comment by tifayuki** [comment]
@masondesu 
I sent a PR to homebrew:
https://github.com/Homebrew/homebrew/pull/48966

The cli will be available when it is merged.

**Comment by fermayo** [comment]
It is now available on brew
