### ISSUE TITLE
docker-cloud repository ls doesn't show repositories from docker hub

### ISSUE THREAD

**Issue by juliocanares** [docker/dockercloud-cli#23]
When running `docker-cloud repository ls` it shows an empty list

```
NAME    IN_USE
```

however if I inspect a repository from my docker hub it works

```
docker-cloud repository inspect juliocanares/hd_node
```

results

```
{
  "name": "juliocanares/hd_node",
  "last_build_date": null,
  "public_url": "https://registry-1.docker.io/_/juliocanares/hd_node/",
  "in_use": false,
  "state": "Empty",
  "registry": "/api/repo/v1/registry/registry-1.docker.io/",
  "build_source": null,
  "dockercloud_action_uri": "",
  "tags": [],
  "resource_uri": "/api/repo/v1/repository/juliocanares/hd_node/"
}
```

**Comment by fellfromhell** [comment]
I'm facing the same issue.

**Comment by tifayuki** [comment]
The api of repository only returns repository on a 3rd repository registry. 
https://docs.docker.com/apidocs/docker-cloud/#external-repository

**Comment by arcticoder** [comment]
Same here. I'm using boot2docker on Windows, ssh'ing into the VM directly.

docker-cloud 1.0.7
