### ISSUE TITLE
Can't access Organisation 

### ISSUE THREAD

**Issue by mjdavies** [docker/dockercloud-cli#36]
Sorry if this isn't a bug, but I can't find any docs on how to accomplish accessing our organisations docker cloud environment with the CLI.

Are there some docs I'm not finding?

I only see my personal accounts details.  That account is an owner of the organisation with admin rights, but whatever I do from the command line, I cant see the organisation elements.

Any tips, greatly appreciated.

**Comment by tifayuki** [comment]
@mjdavies 

You can use `DOCKERCLOUD_NAMESPACE` envvar described in the README: https://github.com/docker/dockercloud-cli#namespace

**Comment by mjdavies** [comment]
Sorry, my bad.  Thanks @tifayuki

**Comment by mjdavies** [comment]
Woops, maybe I spoke to soon.

Hardly any of that documentation works for me, :-(

I'm on el Capitan, I'm install docker-cloud via brew, 1.0.3 is installed.

```
trj260-mdmac:~$ docker-cloud login

Please use "docker login" to log into Docker Cloud with you Docker ID"

Alternatively, you can set the following environment variables:

    export DOCKERCLOUD_USER=<docker username>
    export DOCKERCLOUD_PASS=<docker password>
```

If I then set those variables, anywhere, docker-login still doesn't pick them up.

If I use docker to login, I only see my personal docker cloud elements.

I think the docs are also wrong in places.

Could someone help me?  I'm obviously doing something stupid.

**Comment by mjdavies** [comment]
Upgraded to 1.0.7, still doing something stupid :-(

**Comment by mjdavies** [comment]
ok, got it working.

I setup the DOCKERCLOUD_NAMESPACE to be defined in my ~/.bash_profile and now running docker-cloud commands, after logging in with docker login, and opening a new terminal window(nice one), I can access my orgs details.

Sorry, told you it was something stupid

Thanks
