### ISSUE TITLE
How to access container/node "Last Metric" attributes?

### ISSUE THREAD

**Issue by adambiggs** [docker/dockercloud-cli#40]
The Docker Cloud API reference mentions "Last Metric attributes" for both nodes and containers. I'm trying to build an auto-scaling component on top of the API, but I have no idea how to access these attributes. There doesn't seem to be any other references to these attributes anywhere else...

https://docs.docker.com/apidocs/docker-cloud/?http#node-last-metric-attributes
https://docs.docker.com/apidocs/docker-cloud/?http#container-last-metric-attributes

**Comment by tifayuki** [comment]
Hi @adambiggs 

The two attributes were removed from our API long ago, but somehow the document is not updated. It is not available any more.  We will update the doc ASAP.

Sorry for the inconvenience.
