### ISSUE TITLE
StreamingLog object has no attribute '_namespace'

### ISSUE THREAD

**Issue by robinduckett** [docker/dockercloud-cli#51]
`StreamingLog object has no attribute '_namespace'`

When trying to view a log on a namespace, this is the error I get.

DOCKERCLOUD_NAMESPACE set

**Comment by jmshelby** [comment]
As an update, and a little more information. I am seeing this happen when running docker-cloud cli from MAC OS in v1.0.8, as well as when running cli from the docker container of v1.0.8. But I don't see this bug when running from the docker container with tag: v1.0.7 ... seems to be a bug introduced in version 1.0.8

**Comment by tifayuki** [comment]
I will take a look at it and do a patch ASAP

**Comment by tifayuki** [comment]
@robinduckett @jmshelby 

I have updated the SDK to a new version that contains the fix.
Can you do `pip install -U python-dockercloud` to upgrade the SDK version from `v1.0.11` to `v1.0.12` and try again?

Thank you

**Comment by robinduckett** [comment]
About a month too late, implemented it myself using node / websocket API directly, and no longer use this CLI due to the fact that it didn't seem to support namespaces which is kind of important for the way my client uses Docker Cloud.

Is there anywhere I can log issues against the docker cloud API directly because I've come across a few issues surrounding the implementation of remote execution (no way to send escaped characters, so you can't do things like update the terminal window size of the remote container using control characters \033[ etc) among other things.

**Comment by jmshelby** [comment]
@tifayuki - thanks but i'm just using the pre-built docker image, not really sure how to setup all that pip stuff. We're you able to recreate the issue on your end before you fixed it? if so, then I trust the fix

**Comment by tifayuki** [comment]
@jmshelby 
I have rebuild the image with tag `latest` and `v1.0.9`

**Comment by tifayuki** [comment]
@robinduckett 
Sorry about the late fix. The CLI doesn't directly support namespace with options, but the python SDK supports it. 

To Report API issue. You can either open a support ticket, or go to the docker forum and open an issue(https://forums.docker.com/c/docker-cloud)

**Comment by jmshelby** [comment]
sweet thanks! @tifayuki 

v1.0.9 is working great for me

**Comment by jmshelby** [comment]
Although the bug is fixed in v1.0.9, that version does not seem to be available via homebrew yet ... any word on when the taps are going to be updated?

**Comment by tifayuki** [comment]
@jmshelby 
The homebrew is not updated. I will send a PR for a new version soon.

**Comment by tifayuki** [comment]
The PR for the new version has been merged to homebrew

**Comment by jmshelby** [comment]
thanks Feng
