### ISSUE TITLE
Docker Cloud CLI Swarm mode support

### ISSUE THREAD

**Issue by jmarceli** [docker/dockercloud-cli#57]
Does the Docker Cloud CLI work with Swarm mode?
I've added my "Swarm mode" based Docker swarm by BYOS button inside [docker cloud web app](https://cloud.docker.com), but I can't view it from the `docker-cloud` CLI.

Everything seems to be working fine with the old docker cloud web app (with "Swarm mode" off).

**Comment by tifayuki** [comment]
@jmarceli 
`dockercloud cli` doesn't support swarm mode.
With swarm mode in docker cloud, you can directly use docker cli to talk to your remote swarm cluster. Thus there is no need to add another cli.

**Comment by jmarceli** [comment]
OK. Thanks for the info.

I should probably find out why my swarm login from Docker for Mac app doesn't work as expected (it doesn't open working Swarm Master terminal). I get:
```
Cannot connect to the Docker daemon at unix:///var/folders/9v/dlb6h7m11sddrh8020hlt0f40000gn/T/077358bb-bf7f-4785-b5fb-1a860823b6d7. Is the docker daemon running?
```
But that's probably not related to the Docker Cloud.
